# -*- coding: utf-8 -*-
"""Text to CSV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19-0jDGa6MUKeM_5LepBNUB75uVWigXSj
"""

from google.colab import files
uploaded = files.upload()

file_name = "Analysis.txt"
uploaded[file_name].decode("utf-8")

data = uploaded[file_name].decode("utf-8").split("\n")

data

d = []
for i in data:
  d.append(i.split('\t'))
d

s1 = []
for i in range(len(d)):
  for j in range(len(d[i])):
    s = d[i][j].split(' ')
    s1.append(d[i][j].split('\t'))
    # print(s1)
    # print
    # if s[0]=='Frame':
    #   print(d[i][j])

# s1
names = []
emotions = []
for i in range(len(s1)):
  for j in range(len(s1[i])):
      try:
        if s1[i][0][0]=='n':
          names.append(s1[i][j].split(':')[1])
        if s1[i][0][0]=='S':
          emotions.append(s1[i][j].split(':')[1])
      except:
        continue

# print('Names'+' '+'Emotion')
# for i in range(len(names)):

#   print(names[i]+' '+emotions[i])

import re
for i in range(len(names)):
  names[i] = re.sub(r"[^a-zA-Z' ']","",names[i])
  names[i] = names[i].lstrip()
  names[i] = names[i].rstrip()

unique_names = set(names)

# unique_names

